@extends('layouts.storefront')
@section('title', 'Địa chỉ')
@section('page', 'addresses')
@section('content')
@if($tv4Preview)
<main><section class="page-hero page-hero--compact"><div class="container"><nav class="breadcrumbs"><a href="{{ url('/') }}{{ $tv4Preview ? '?preview=1' : '' }}">Trang chủ</a><span>/</span><span>Địa chỉ</span></nav><h1>Địa chỉ giao hàng</h1></div></section><section class="section container account-layout"><aside data-account-nav></aside><div class="account-content"><div class="panel-heading"><div><span class="eyebrow">Sổ địa chỉ</span><h2>Chọn nơi nhận hàng</h2></div><button class="btn btn--primary" data-open-address><i data-feather="plus" aria-hidden="true"></i> Thêm địa chỉ</button></div><div class="address-grid"><article class="address-card is-default"><div><span class="status-badge status-badge--success">Mặc định</span><h3>Nguyễn Văn An</h3><p>0901 234 567</p><p>12 Nguyễn Huệ, Phường Sài Gòn, TP.HCM</p></div><div><button class="link-button">Chỉnh sửa</button><button class="link-button link-button--danger">Xóa</button></div></article><article class="address-card"><div><h3>Nguyễn Văn An</h3><p>0901 234 567</p><p>45 Võ Văn Ngân, Phường Thủ Đức, TP.HCM</p></div><div><button class="link-button">Đặt mặc định</button><button class="link-button">Chỉnh sửa</button></div></article></div></div></section></main><dialog class="modal" id="address-modal"><form method="dialog" class="modal__card" data-address-form><div class="modal__head"><div><span class="eyebrow">Địa chỉ mới</span><h2>Thông tin nhận hàng</h2></div><button value="cancel" aria-label="Đóng"><i data-feather="x" aria-hidden="true"></i></button></div><div class="form-grid"><label>Người nhận<input required placeholder="Họ và tên"></label><label>Số điện thoại<input required placeholder="0901 234 567"></label></div><label>Địa chỉ đầy đủ<textarea rows="3" required placeholder="Số nhà, đường, phường/xã, tỉnh/thành phố"></textarea></label><label class="check-inline"><input type="checkbox"> Đặt làm địa chỉ mặc định</label><div class="form-actions"><button class="btn btn--outline" value="cancel">Hủy</button><button class="btn btn--primary" value="save">Lưu địa chỉ</button></div></form></dialog>
@else
<main id="live-main" class="container section" aria-live="polite"><div class="panel"><p>Đang tải…</p></div></main>
@endif
@endsection
